In [1]:
import pandas as pd
import numpy as np
import country_converter as coco
import os

In [2]:
pd.options.display.float_format = "{:,.2f}".format

In [3]:
df = pd.read_csv("../data/raw/netflix_titles.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [5]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [6]:
null_counts = df.isna().sum()
null_counts[null_counts > 0]

director      2634
cast           825
country        831
date_added      10
rating           4
duration         3
dtype: int64

In [7]:
df["date_added"] = pd.to_datetime(df["date_added"].str.strip(), errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   datetime64[ns]
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: datetime64[ns](1), int64(1), object(10)
memory usage: 825.8+ KB

In [8]:
df[["director", "cast", "country"]] = df[["director", "cast", "country"]].fillna("Unknown")

In [9]:
df[df["duration"].isna()]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,2017-04-04,2017,74 min,NaN,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,2016-09-16,2010,84 min,NaN,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,2016-08-15,2015,66 min,NaN,Movies,The comic puts his trademark hilarious/thought...

In [10]:
df["duration"] = df["duration"].fillna(df["rating"])
df.loc[df["rating"].str.contains("min", na=False), "rating"] = "Unknown"

In [11]:
df = df.dropna(subset=["date_added", "rating"])

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8793 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8793 non-null   object
 1   type          8793 non-null   object
 2   title         8793 non-null   object
 3   director      8793 non-null   object
 4   cast          8793 non-null   object
 5   country       8793 non-null   object
 6   date_added    8793 non-null   datetime64[ns]
 7   release_year  8793 non-null   int64
 8   rating        8793 non-null   object
 9   duration      8793 non-null   object
 10  listed_in     8793 non-null   object
 11  description   8793 non-null   object
dtypes: datetime64[ns](1), int64(1), object(10)
memory usage: 893.0+ KB

In [13]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [14]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8793 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8793 non-null   object
 1   type          8793 non-null   object
 2   title         8793 non-null   object
 3   director      8793 non-null   object
 4   cast          8793 non-null   object
 5   country       8793 non-null   object
 6   date_added    8793 non-null   datetime64[ns]
 7   release_year  8793 non-null   int64
 8   rating        8793 non-null   object
 9   duration      8793 non-null   object
 10  listed_in     8793 non-null   object
 11  description   8793 non-null   object
dtypes: datetime64[ns](1), int64(1), object(10)
memory usage: 893.0+ KB

In [16]:
df["temp_title"] = df["title"].str.strip().str.lower()
title_duplicates = df[df.duplicated(subset=["temp_title", "type"], keep=False)]
title_duplicates.sort_values(by="temp_title")[["title", "type", "release_year", "country"]]

                         title     type  release_year                  country
3371              Consequences    Movie          2014                   Turkey
6529             Consequences     Movie          2014                   Turkey
303       Esperando la carroza    Movie          1985                Argentina
6705      Esperando La Carroza    Movie          1985                Argentina
159             Love in a Puff    Movie          2010                Hong Kong
7345            Love In A Puff    Movie          2010                Hong Kong
1270  Sin senos sí hay paraíso  TV Show          2018  United States, Colombia
8022  Sin Senos sí Hay Paraíso  TV Show          2018  United States, Colombia

In [17]:
df["title"] = df["title"].str.strip().str.lower()
df = df.drop_duplicates(subset=["title", "type"], keep="first")
df.drop(columns=["temp_title"], inplace=True)

In [18]:
df.duplicated(subset=["title", "type"]).sum()

np.int64(0)

In [19]:
df["genre"] = df["listed_in"].str.split(",").str[0].str.strip()
df = df.drop(columns=["listed_in"])

In [20]:
df["country"] = df["country"].str.split(",").str[0].str.strip()

In [21]:
cc = coco.CountryConverter()

country_mapping = {
    "Soviet Union": "Russia",
    "West Germany": "Germany",
    "East Germany": "Germany"
}
df["country"] = df["country"].replace(country_mapping)

df["ISO"] = cc.pandas_convert(series=df["country"], to="ISO3", not_found=None)

Unknown not found in regex
 not found in regex

In [22]:
df.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,description,genre,ISO
0,s1,Movie,dick johnson is dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,"As her father nears the end of his life, filmm...",Documentaries,USA
1,s2,TV Show,blood & water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"After crossing paths at a party, a Cape Town t...",International TV Shows,ZAF
2,s3,TV Show,ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,To protect his family from a powerful drug lor...,Crime TV Shows,Unknown
3,s4,TV Show,jailbirds new orleans,Unknown,Unknown,Unknown,2021-09-24,2021,TV-MA,1 Season,"Feuds, flirtations and toilet talk go down amo...",Docuseries,Unknown
4,s5,TV Show,kota factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,In a city of coaching centers known to train I...,International TV Shows,IND
5,s6,TV Show,midnight mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",Unknown,2021-09-24,2021,TV-MA,1 Season,The arrival of a charismatic young priest brin...,TV Dramas,Unknown
6,s7,Movie,my little pony: a new generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",Unknown,2021-09-24,2021,PG,91 min,Equestria's divided. But a bright-eyed hero be...,Children & Family Movies,Unknown
7,s8,Movie,sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...",United States,2021-09-24,1993,TV-MA,125 min,"On a photo shoot in Ghana, an American model s...",Dramas,USA
8,s9,TV Show,the great british baking show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,2021-09-24,2021,TV-14,9 Seasons,A talented batch of amateur bakers face off in...,British TV Shows,GBR
9,s10,Movie,the starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,2021-09-24,2021,PG-13,104 min,A woman adjusting to life after a loss contend...,Comedies,USA

In [ ]:
df["type"] = df['type'].astype("category")
df["rating"] = df["rating"].astype("category")
df["genre"] = df["genre"].astype("category")

df["cast"] = df["cast"].str.lower().str.strip()
df["director"] = df["director"].str.lower().str.strip()

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8789 entries, 0 to 8806
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8789 non-null   object
 1   type          8789 non-null   category
 2   title         8789 non-null   object
 3   director      8789 non-null   object
 4   cast          8789 non-null   object
 5   country       8789 non-null   object
 6   date_added    8789 non-null   datetime64[ns]
 7   release_year  8789 non-null   int64
 8   rating        8789 non-null   category
 9   duration      8789 non-null   object
 10  description   8789 non-null   object
 11  genre         8789 non-null   category
 12  ISO           8789 non-null   object
dtypes: category(3), datetime64[ns](1), int64(1), object(8)
memory usage: 783.2+ KB

In [28]:
os.makedirs("../data/processed", exist_ok=True)
df.to_csv("../data/processed/netflix_titles_cleaned.csv", index=False)